### PR TITLE
Google Maps MVP Update

### PR DESCRIPTION
**Pull request by tranzilla**
Google maps displaying gigs instead of venue, changed pins to circle and removed the event listener to hide the locations.

Changes: 
1. Updated the SQL - MUST RUN new script in 06102019.sql --> this links the markers (used in google maps) to the information on Gigs
2. Added google maps back into the welcome_page.php and updated the javascript to display a circle around the venues and limited the zoom capability (so users don't zoom into the exact location)
3. phpsqlajax_genxml.php --> this changes the queries to gigs using inner joins to link all 3 tables (Gigs, Company, and Markers)

Working instance: htduong.com/gig-central

### CODE REVIEW

**Comment by thomaskise** [comment]
@tranzilla 
Looks fabulous! And thanks for adding the link to working code. One question: Does this require an update to "Add Gig" to insert the markers in the db when the Gig is created?

**Comment by tranzilla** [comment]
@thomaskise 
Unfortunately, it's not integrated with the Add Gig. The table Makers is used exclusively for Google Maps and it requires latitude and longitudinal coordinates which needs to be manually inputted (it's not in the Gigs table). 

I think this could be done but the Gigs Table will need to be rewritten to include lat and lng I'm sure there is a function that we can write to exact the lat and lng when an address is inputted but due to time constraint, I'm not able to do that.

**Comment by andylwilson** [comment]
I think it looks fantastic Tran! You make a great observation @thomaskise , but I think it's well worth merging for the time being, and leaving the actual programatic integration with the gig data as an open issue for the next quarter's team. I think Tran did a great job here, and it makes the home page a lot more interesting. :) That said, when we discuss the home page design later today, we might go over how we can slightly alter the layout, which I think should be a very simple change.

**Comment by thomaskise** [comment]
Sounds good. Just to be sure I understand, we'll need to build some sort of process to automate longitude/latitude for the Gig locations on the map.

**Comment by tranzilla** [comment]
@thomaskise Correct. For the next quarter, they need to do two things:
1. Rewrite database- Gigs table to include lat and lng fields 
2. Write a function to pull lat and lng when an address is added to "Add Gig" and have that inserted into the field "lat" and "lng" in the Gigs table. 

*If they are able to achieve that, there will be no more manual entry of lat and lng into Markers table.

**Comment by andylwilson** [comment]
Yes, I believe we'll need to create some form of mechanism/function to convert the addresses to lat long (something's like this https://www.latlong.net/convert-address-to-lat-long.html), then create another function for automatically inserting them on the map when a gig is added. Definitely outside the scope for the remainder of this class, but I think could be a cool project for the next class.

**Pull request merged**
