### PR TITLE
Gig previews new format

### PR DESCRIPTION
**Pull request by ianbeard0159**
I redesigned the look of the gig previews page. I have these changes implemented on my development instance here: http://www.ianbeard0159.com/gig-central/gig

### CODE REVIEW

**Comment by ianbeard0159** [comment]
I made the requested changes. The company name is no longer shown on the display and has been removed from the search filter.

**Comment by thomaskise** [comment]
Hi Ian ... thanks for making these changes. This looks great. I am getting an error though when I try to apply the filters. To reproduce:
Go to the gig list page
click on "Apply Filter"
Result:
image

**Comment by ianbeard0159** [comment]
I fixed the issue, but I made the changes in their own pull request (#242) rather than adding the changes to this one.

**Comment by thomaskise** [comment]
OK ... cool ... thanks.  I'm going to go ahead and merge this one (Unless I find there are some tricks I'm not aware of merging from the fork), I'll  check the other a bit later.

**Comment by thomaskise** [comment]
Closes task #239

**Pull request merged**
