### PR TITLE
Post gig form validation

### PR DESCRIPTION
**Pull request by tranzilla**
Edit html in view/gig/add to display form error(line69) and change the "State" selection from a dropdown box to the text input (line 62-63)

In controllers/gig: add form validation rules for all the form input.

See Dev Instance for working form validation: http://htduong.com/gig-central/gig/add

### CODE REVIEW

**Comment by thomaskise** [comment]
This pull request broke state dropdown selection. Instead of deleting lines 62 - 68, custom_config.php should have been updated with state codes array. I'm submitting a fix in a few minutes. I also plan on presenting a report tomorrow in class on how this works. See references:
-- custom_config_sample.php
-- pull request #154: https://github.com/gig-central/gig-repo-1/pull/154

**Comment by andylwilson** [comment]
Oh crap, I see that now Thom, sorry about that. The rest of the validation changes should still be good. Btw, I merged another pull request in the mean time since you posted this comment, so please make sure to fetch the latest master before making the fix to the state drop down.

**Comment by andylwilson** [comment]
> This pull request broke state dropdown selection. Instead of deleting lines 62 - 68, custom_config.php should have been updated with state codes array. I'm submitting a fix in a few minutes. I also plan on presenting a report tomorrow in class on how this works. See references:
> -- custom_config_sample.php
> -- pull request #154: #154

Oh crap, I see that now Thom, sorry about that. The rest of the validation changes should still be good. Btw, I merged another pull request in the mean time since you posted this comment, so please make sure to fetch the latest master before making the fix to the state drop down.

**Comment by thomaskise** [comment]
All is good, and pull request #218 is ready for review.

I didn't fetch ... but the files in Esteban's request #217 are different, so there should be no conflict.

**Comment by andylwilson** [comment]
Yep you're right, merged! Thanks!

**Pull request merged**
