### PR TITLE
Enhance gig details auth

### PR DESCRIPTION
**Pull request by esteban-gs**
refactor-login-controller: adds error handling and bootswatch feedback

### CODE REVIEW

**Comment by esteban-gs** [comment]
@andylwilson . should be up to date now

**Comment by esteban-gs** [comment]
#211

**Comment by andylwilson** [comment]
Excellent, this looks good! I didn't know the credentials so I couldn't test a successful login, but the validation and the unsuccessful login work! Great work man.

**Comment by thomaskise** [comment]
Andy ... the register link is still available ... you can create an account.

Good work both of you ... burning the midnight oil, as they say.

**Comment by thomaskise** [comment]
And Esteban ... check it out! 👍 

Hi Thom, Welcome to GigCentral website!

Fixed my logon problem!  Woo-hoo!

**Comment by thomaskise** [comment]
Opps ... but now getting: Please log in to see gig details after logon.

**Comment by andylwilson** [comment]
Good looking out on the register link, I removed that and submitted a pull request with you assigned Thom. I know you're an admin too, but it's late and pull requests really aren't your responsibility, so I'll assign Carolina and Craig as well.

**Pull request merged**
