### PR TITLE
enhance contact process

### PR DESCRIPTION
**Pull request by esteban-gs**
- Enhancement: Don't send email or submit form until reCaptcha response = success.
- reinstated `application/views/contact/view.php`

### CODE REVIEW

**Comment by esteban-gs** [comment]
This new change ensures email is not sent, OR contact form data written to the DB, when recatcha validation fails.

**Comment by esteban-gs** [comment]
Also, i reinstated the view view, just in case it's used somewhere else, but it's definitely not called from the Contact controller

**Comment by esteban-gs** [comment]
I'll test of maybe it's called from the admin side. If not I'll remove it on my next commit

**Comment by craigbpeterson** [comment]
Nice dude! Makes total sense.

**Pull request merged**
