### PR TITLE
Add lables to filters

### PR DESCRIPTION
**Pull request by michaelnomura**
Add three drop downs to gig/index.php that make the gigs a little easier to navigate. Moved function out of gig/index.php to Gig_model.php

### CODE REVIEW

**Comment by gillilands19** [comment]
Being Reworked! Don't Review Yet.

**Comment by michaelnomura** [comment]
Should be ready to deploy

**Comment by michaelnomura** [comment]
What error did you get with the drop down i'll take a look?

**Comment by michaelnomura** [comment]
Also check if the search is working since it is using the same function in the model

**Comment by gillilands19** [comment]
That unique_multidim_array method is a pretty clever way to abstract looping levels deep on the getGigs object. That's useful enough that we might want to put it in the helper functions file. Great work.

The drop downs and search functionalitu seems to be working just fine for me @Ariton84. 

@michaelnomura, there are a few changes that need to be made though. Make sure you are following PSR standards. One thing I see is your method names need to be in camel case.

See PSR 1 and 2: https://www.php-fig.org/psr/

Run through real quick and make sure you are following naming standards. In everything you've created. Don't worry about that which you haven't. We will make a task for someone to review the existing codebase and refactor to PSR compliance.

**Comment by gillilands19** [comment]
Also, please make sure you merge the most recent Master into this branch!

**Comment by michaelnomura** [comment]
Sorry though it was current when I sent the pull request. I will do from the CLI instead of the desktop app to make sure

**Comment by michaelnomura** [comment]
Ready to test again if someone has a chance, also fixed naming convention to camel case.

**Comment by gillilands19** [comment]
All looks good. Great Work Michael!

**Pull request merged**
