### PR TITLE
fix-ugly-validation-fail

### PR DESCRIPTION
**Pull request by esteban-gs**
- Created a landing page for failed validation case: no Recaptcha checkbox selected. 

- Created a new view, failed.

-See fix live: https://www.tegs.tech/gig-central/contact/

-issue #158 has instructions to reproduce.

-please merge and delete.

#158

### CODE REVIEW

**Comment by craigbpeterson** [comment]
@thomaskise's idea is better than mine.

**Comment by esteban-gs** [comment]
The way that the validation code is written: if( POST is empty) show form, else process recaptcha
Doesn't allow errors to be displayed before form is submitted. 
It may require a re-write of the form handling.

**Comment by esteban-gs** [comment]
We may have to also mess with application/libraries/Recaptcha.php

**Comment by thomaskise** [comment]
The reCaptcha is probably Google stuff ... that's where Bill's other
reCaptcha comes from.  It's really messy .... I've had some issues with it,
and I get "reports" from various chck functions that some of the code might
be invvalid. One mssage I got in the Dev Tools Console said that it was  a
scripting risk.

**Comment by esteban-gs** [comment]
I wonder if it can be handled by javascript. I don't know enough to atempt it.

**Comment by thomaskise** [comment]
I'd think there is a way to stop progression if reCaptcha has not been
performed, but if this is not the case, it shouldn't be too much to figure
out how to do a redirect within the MVC structure passing data back to the
index.php. This would be something like what we did when we implemented the
Flickr RSS feed.

**Pull request merged**
